# Generated by Django 3.1.4 on 2020-12-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=20)),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('userPic', models.ImageField(default='defo', upload_to='documents/')),
                ('userName', models.CharField(max_length=50)),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('commentTitle', models.CharField(max_length=40)),
                ('comment', models.TextField()),
            ],
        ),
    ]
