# Generated by Django 3.1.4 on 2021-03-20 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTitle', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('star', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('countgood', models.IntegerField(default=0)),
                ('countbad', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('image_path', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPic', models.ImageField(default='documents/default_image1.png', upload_to='documents/')),
                ('userComment', models.TextField(default='コメントがありません')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goodbad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(null=True)),
                ('bad', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodbad_owner', to='movieist.review')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.IntegerField(null=True)),
                ('follower', models.IntegerField(null=True)),
                ('countfollowing', models.IntegerField(default=0)),
                ('countfollower', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
