# Generated by Django 3.1.4 on 2021-01-24 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTitle', models.CharField(max_length=40)),
                ('comment', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPic', models.ImageField(default='https://drive.google.com/file/d/1q-7ho_qbNDOtM5pj5FEWPNFWfVzeg4lt/view?usp=sharing', upload_to='documents/')),
                ('userComment', models.TextField(default='コメントがありません')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
