# Generated by Django 3.1.4 on 2021-01-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPic',
            field=models.ImageField(default='documents/default_image1.png', upload_to='documents/'),
        ),
    ]
