# Generated by Django 3.1.4 on 2021-01-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieist', '0002_auto_20210124_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPic',
            field=models.ImageField(default='movieist/media/documents/default_image1.png', upload_to='documents/'),
        ),
    ]
