# Generated by Django 3.1.4 on 2021-01-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieist', '0003_auto_20210125_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPic',
            field=models.ImageField(default='documents/default_image1.png', upload_to='documents/'),
        ),
    ]
