# Generated by Django 3.1.4 on 2021-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieist', '0004_auto_20210125_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
